### ISSUE TITLE
Name of galvanometer used

### ISSUE THREAD

**Issue by kentaroy47** [Ildaron/Laser_control#5]
Great work!
We are trying to replicated this work, but confused what kind of galvanometer is used.

Can you point out the part number of the galvanometer used? That would be great!

**Comment by Ildaron** [comment]
@kentaroy47 こんにちは、あなたのメッセージをありがとう
私は安いガルバノメーターを使った 
https://aliexpress.ru/item/33024452187.html?spm=a2g2w.productlist.list.2.d06e28b4zXsZNO&sku_id=12000028700246933
質問があればはお知らせください

**Comment by kentaroy47** [comment]
Thanks for the pointer! This will help greatly
ありがとうございます
