### ISSUE TITLE
problem with mirror_control circuit

### ISSUE THREAD

**Issue by Pure-Zzzz** [Ildaron/Laser_control#7]
Hello, I saw your project and purchased some equipment like yours, but I had some problems with the digital-to-analog circuit connections. Did you use two mcp4922? How do they work? Can I get some details like photos of your circuit? Thank you very much

**Comment by Ildaron** [comment]
Hi 
https://github.com/Ildaron/Laser_control/tree/master/2.Jetson_code/2.1_mirror_control
